### ISSUE TITLE
Cod4x Server No guids

### ISSUE THREAD

**Issue by Sc4rface99** [callofduty4x/CoD4x_Server#95]
Hi, 

I´m running cod4x mod on my Linux Server it is working good but I have a problem! 

Admin Plugins like b3 are not working because players do not have a guid 

The guid for all players is 0!

How to fix this?

Thanks for help 

Best Regards Sc4rface

**Comment by D4edalus** [comment]
are you using the auth-lib? http://cod4x.me

**Comment by Sc4rface99** [comment]
Yes I use it but its not working because of the Issue I mentioned in my post

**Comment by D4edalus** [comment]
are you still hanging on this?
symbol _ZNSt3tr18__detail12__prime_listE, version GLIBCXX_3.4.10 not defined in file libstdc++.so.6 with link time reference

if so: you said you installed libstdc++ .. did you install it for the correct architecture?
also the cod4x downloads come with a prepackaged libstdc++.so.6 which you can delete

**Comment by Sc4rface99** [comment]
Now I´ve got a new problem as following:

symbol _ZNSt8__detail15_List_node_base7_M_hookEPS0_, version GLIBCXX_3.4.15 not defined in file libstdc++.so.6 with link time reference

**Comment by D4edalus** [comment]
after doing what

**Comment by Sc4rface99** [comment]
After installing  libstdc++.so.6 for the correct architecture

**Comment by Sc4rface99** [comment]
The problem GLIBCXX_3.4.10 is fixed but now the problem is G
LIBCXX_3.4.15

**Comment by D4edalus** [comment]
if you are on a debian based system you can try 
sudo apt-get install gcc-multilib g++-multilib
also to find here: https://github.com/callofduty4x/CoD4x_Server
i guess u tried that already?

**Comment by armyboylegend** [comment]
i removed libgcc_s.so.1 & libstdc++.so.6 for cod4 directory and this error fixed

"symbol ZNSt8__detail15_List_node_base7_M_hookEPS0, version GLIBCXX_3.4.15 not defined in file libstdc++.so.6 with link time reference"

but still after status command no GUIDs are shown

"num score ping playerid          steamid           name                             lastmsg address                                              qport rate
         --- ----- ---- ----------------- ----------------- -------------------------------- ------- ---------------------------------------------------- ----- -----
           0     0  237 [I:0:0]           [I:0:0]           poker^7                                  0 xxx.xxx.xxx.xxx:28960                                   7644 25000"

how can i fix it?

**Comment by D4edalus** [comment]
still unsolved?

**Comment by armyboylegend** [comment]
no resolved. none has added any solution. on windows server everything worked fine while i tried all versions of ubuntu and cetnos but issue is not solved and none from cod4x creators are helping in it

**Comment by IceNinjaman** [comment]
Which version are you trying with now? I hope latest one as it shouldn't have these dependencies.

**Comment by AlexanderCurl** [comment]
The problem is the GUID now. Yeah the GUID is completly removed the git releases, you should download the latest precomplied bin from the cod4x website, that's got GUID.

**Comment by D4edalus** [comment]
closed as no further questions were asked, please reopen if needed

**Comment by XxXShashikaXxX** [comment]
B3 Commands not working cod4x1.8
:C

**Comment by AlexanderCurl** [comment]
It is working, you can find plenty of topics on the forum. Use the search field.
You can close this again @D4edalus
